# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 python:3.10.16

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements/pipeline.txt .
RUN pip install --no-cache-dir -r pipeline.txt

# Copy the preprocessing script and utility functions
COPY run_pipeline.py .
COPY functions/ functions/
COPY .env .env

# Run the script when the container launches
CMD ["python", "run_pipeline.py"]