# Use an official Python runtime as a parent image
FROM --platform=linux/amd64 python:3.10.16

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements/validation.txt .
RUN pip install --no-cache-dir -r validation.txt

# Copy the preprocessing script and utility functions
COPY data_quality_check.py .
COPY functions/ functions/
COPY .env .env


# Run the script when the container launches
CMD ["python", "data_quality_check.py"]