# Use an official Python runtime as a parent image
FROM python:3.10.16

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements/neo4j.txt .
RUN pip install --no-cache-dir -r neo4j.txt

# Copy the preprocessing script and utility functions
COPY upload_to_neo4j.py .
COPY functions/ functions/
COPY .env .env

# Run the script when the container launches
CMD ["python", "upload_to_neo4j.py"]